### ISSUE TITLE
Cache our local images

### ISSUE THREAD

**Issue by chris-anderson67** [JumboCode/NorthShoreCDC#140]
Because of how expo works, even the images that we have in our PUAMapp folder are downloaded at runtime from expo's servers (don't ask me why). This should include all the images that we have saved locally to our folder, and might involve moving them into a subdirectory.
 
We have to manually cache them with using Expo's api: https://docs.expo.io/versions/latest/guides/offline-support.html. Also see https://docs.expo.io/versions/latest/guides/preloading-and-caching-assets.html.

**Comment by bsteephenson** [comment]
caching with iOS -- https://facebook.github.io/react-native/docs/images.html#cache-control-ios-only
